#!/usr/bin/env python3
"""Phase 0 passer audit: BBA-reject check over the released Package/*.pbn.

For each board, find the "quiet" partnership -- the side that passes throughout the
scripted auction -- then assert the true scripted auction via bba-cli's
`--auction-prefix` and ask BBA (EPBot) what that side would do at each of its turns.
Any non-pass => a *biddable passer*: a generated opponent hand that would break the
lesson's intended quiet auction.

This changes no fills. It measures the blast radius of the loose fill constraints
(see Tools/passer-fill-bba-redesign.md, issue #21) and doubles as a regression
baseline ("N biddable boards today -> 0 after the redesign").

Usage:
    python3 Tools/audit_passers.py [lesson ...]      # default: all Package/*.pbn
    python3 Tools/audit_passers.py NMF Reverse       # a subset, by basename

Writes a per-board CSV next to Package/ (audit_passers_results.csv) and prints a
per-lesson summary + offender list. Requires the native Mac bba-cli:
    ~/Development/GitHub/BBA-tools/bba-cli/target/release/bba-cli
"""
import glob, os, re, subprocess, sys, csv, tempfile
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BBA = os.environ.get("BBA_CLI",
        os.path.expanduser("~/Development/GitHub/BBA-tools/bba-cli/target/release/bba-cli"))
CONV = os.path.join(REPO, "Tools", "BAKER-BRIDGE.bbsa")
MISSING_BIDS = os.path.join(REPO, "Tools", "missing_bids.csv")
OUT_CSV = os.path.join(REPO, "Tools", "audit_passers_results.csv")
SEATS = ["N", "E", "S", "W"]
CALL_RE = re.compile(r'^(pass|x|xx|dbl|rdbl|[1-7](c|d|h|s|nt))$', re.I)


def fill_lessons():
    """Lesson basenames whose passer hands are generated by the fill step."""
    s = set()
    if not os.path.exists(MISSING_BIDS):
        return s
    with open(MISSING_BIDS, encoding="utf-8", errors="replace") as f:
        for row in csv.DictReader(f):
            sub = (row.get("Subfolder") or "").strip()
            if sub:
                s.add(sub.split("/")[0])  # "Bidpractice/Set1" -> "Bidpractice"
    return s


def norm_prefix_tok(t):
    """Scripted call token -> bba-cli prefix token (Pass/X/XX/{1-7}{C|D|H|S|NT})."""
    u = t.strip().upper()
    if u == "PASS": return "Pass"
    if u in ("X", "DBL"): return "X"
    if u in ("XX", "RDBL"): return "XX"
    m = re.match(r'^([1-7])(C|D|H|S|N|NT)$', u)
    if m:
        suit = "NT" if m.group(2) in ("N", "NT") else m.group(2)
        return m.group(1) + suit
    return None


def is_pass(tok):
    return tok.strip().upper() == "PASS"


def parse_boards(path):
    """Yield board dicts: number, dealer, deal, vuln, calls (raw scripted tokens)."""
    lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    boards, cur, i = [], None, 0

    def tagval(line):
        m = re.match(r'^\[(\w+)\s+"(.*)"\]', line)
        return (m.group(1), m.group(2)) if m else (None, None)

    while i < len(lines):
        ln = lines[i]
        if ln.startswith("[Board "):
            if cur: boards.append(cur)
            cur = {"number": tagval(ln)[1], "dealer": None, "deal": None,
                   "vuln": "None", "calls": []}
        elif cur is not None and ln.startswith("[Dealer "):
            cur["dealer"] = tagval(ln)[1]
        elif cur is not None and ln.startswith("[Deal "):
            cur["deal"] = tagval(ln)[1]
        elif cur is not None and ln.startswith("[Vulnerable "):
            cur["vuln"] = tagval(ln)[1]
        elif cur is not None and ln.startswith("[Auction "):
            j, done = i + 1, False
            while j < len(lines) and not done:
                s = lines[j]
                if s.startswith("[") or s.startswith("{") or s.strip() == "":
                    break
                for t in s.split():
                    if t.startswith("="):        # note reference, e.g. =1=
                        continue
                    if CALL_RE.match(t):
                        cur["calls"].append(t)
                    else:                         # "all" (all-pass) / commentary => stop
                        done = True
                        break
                j += 1
            i = j - 1
        i += 1
    if cur: boards.append(cur)
    return boards


def quiet_side(dealer, calls):
    """Return (set_of_quiet_seats, per_seat_turns) or None if no single quiet side."""
    if dealer not in SEATS or not calls:
        return None
    start = SEATS.index(dealer)
    ns, ew = [], []
    turns = {s: [] for s in SEATS}
    for p, c in enumerate(calls):
        seat = SEATS[(start + p) % 4]
        turns[seat].append((p, c))
        (ns if seat in ("N", "S") else ew).append(c)
    ns_quiet = bool(ns) and all(is_pass(c) for c in ns)
    ew_quiet = bool(ew) and all(is_pass(c) for c in ew)
    if ns_quiet and not ew_quiet: return ({"N", "S"}, turns)
    if ew_quiet and not ns_quiet: return ({"E", "W"}, turns)
    return None


def run_bba(deal, dealer, vuln, prefix_tokens, tmp):
    inp, outp = os.path.join(tmp, "in.pbn"), os.path.join(tmp, "out.pbn")
    with open(inp, "w") as f:
        f.write('[Event ""]\n[Board "1"]\n'
                f'[Dealer "{dealer}"]\n[Vulnerable "{vuln}"]\n[Deal "{deal}"]\n\n')
    cmd = [BBA, "-i", inp, "-o", outp,
           "--ns-conventions", CONV, "--ew-conventions", CONV]
    if prefix_tokens:
        cmd += ["--auction-prefix", " ".join(prefix_tokens)]
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    lines = open(outp, encoding="utf-8", errors="replace").read().splitlines()
    toks = []
    for i, ln in enumerate(lines):
        if ln.startswith("[Auction "):
            j = i + 1
            while j < len(lines):
                s = lines[j]
                if s.startswith("[") or s.strip() == "":
                    break
                toks += [t for t in s.split() if not t.startswith("=")]
                j += 1
            break
    return toks


def audit(lessons, tmp):
    fills = fill_lessons()
    records = []
    for path in lessons:
        lesson = os.path.splitext(os.path.basename(path))[0]
        for b in parse_boards(path):
            rec = {"lesson": lesson, "board": b["number"],
                   "fill_lesson": lesson in fills, "status": "", "detail": ""}
            qs = quiet_side(b["dealer"], b["calls"])
            if qs is None:
                rec["status"] = "competitive_or_passedout"
                records.append(rec); continue
            quiet, turns = qs
            pref = [norm_prefix_tok(c) for c in b["calls"]]
            if any(t is None for t in pref):
                rec["status"] = "unparseable_auction"; records.append(rec); continue
            offenses = []
            for seat in sorted(quiet):
                for (p, _c) in turns[seat]:
                    toks = run_bba(b["deal"], b["dealer"], b["vuln"], pref[:p], tmp)
                    got = toks[p] if p < len(toks) else "?"
                    if not is_pass(got):
                        offenses.append(f"{seat}@t{p}:{got}")
                        break  # first offense per seat
            rec["status"] = "biddable" if offenses else "clean"
            rec["detail"] = ",".join(offenses)
            records.append(rec)
    return records


def main():
    args = sys.argv[1:]
    if args:
        lessons = [os.path.join(REPO, "Package", a if a.endswith(".pbn") else a + ".pbn")
                   for a in args]
    else:
        lessons = sorted(glob.glob(os.path.join(REPO, "Package", "*.pbn")))

    with tempfile.TemporaryDirectory() as tmp:
        records = audit(lessons, tmp)

    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["lesson", "board", "fill_lesson", "status", "detail"])
        w.writeheader(); w.writerows(records)

    per = defaultdict(lambda: defaultdict(int))
    fill_of = {}
    for r in records:
        per[r["lesson"]][r["status"]] += 1
        fill_of[r["lesson"]] = r["fill_lesson"]
    print(f"{'lesson':<28} {'tot':>4} {'quiet':>5} {'biddable':>8} {'compet':>7}  fill")
    tot_bidd = 0
    for lesson in sorted(per):
        d = per[lesson]
        bidd = d["biddable"]; tot_bidd += bidd
        quiet = d["clean"] + d["biddable"]
        flag = "  <==" if bidd else ""
        print(f"{lesson:<28} {sum(d.values()):>4} {quiet:>5} {bidd:>8} "
              f"{d['competitive_or_passedout']:>7}  {'Y' if fill_of[lesson] else ''}{flag}")
    print(f"\nTOTAL biddable-passer boards: {tot_bidd}")
    print(f"CSV: {OUT_CSV}\n")
    print("--- biddable boards ---")
    for r in records:
        if r["status"] == "biddable":
            print(f"  {r['lesson']:<12} b{r['board']:<3} {r['detail']}"
                  f"  {'[FILL]' if r['fill_lesson'] else ''}")


if __name__ == "__main__":
    main()
